### ISSUE TITLE
Add new tags containing spaces

### ISSUE THREAD

**Issue by martinmaillard** [vhf/resrc#28]
In the add interface, "space" creates the tag. 
In the edit/suggest interface, it does nothing.

I guess behaviour should stay consistent throughout all the interfaces. And we need a way to add new tags containing spaces.

**Comment by vhf** [comment]
JS is the same all over, no idea why spaces create tags. I'll investigate,
could be related to the suggest tag feature.

The way to add tags containing spaces is to used double quotes. I thought
it was obvious enough. Shall I add a tooltip or a line somewhere to explain
this ?
