### ISSUE TITLE
Add new link failed

### ISSUE THREAD

**Issue by J-F-Liu** [vhf/resrc#60]
I registered as a new user, the add link page doesn't work, displays Server Error (500).

**Comment by Kaylors** [comment]
Same happening for me.

**Comment by vhf** [comment]
I think I just fixed it. Could you try again?

**Comment by Kaylors** [comment]
Worked.

**Comment by Kaylors** [comment]
Worked.

*Shuvomay Das,*
shuvophoenix@gmail.com
+91 9004743902
