### ISSUE TITLE
reSRC.io data

### ISSUE THREAD

**Issue by J5lx** [vhf/resrc#61]
When I just went to <http://resrc.io/> again I was welcomed by a blank page with a good-bye-message. While this message gives a good overview I was wondering what happened to the data (i.e. the resources), whether it died along with the SSD or not. It seems like the Wayback Machine archived most of the pages, but it is pretty slow (at least for me), and hackr.io seems to cover much less resources. If you do not want / are not able to continue the hosting of reSRC.io like before, is there at least a way of *somehow* retaining access to the resources of it so people can have a look at them and maybe even migrate them to sites like hackr.io?

Please excuse me if this is the wrong place for this kind of question, but i didn't find any other communication channels that seemed suitable.

**Comment by vhf** [comment]
Thanks for your message. The data is mostly fine. The few latest resources were not recovered, but I'm only talking about 100-200 resources here.

I'm currently in contact with the hackr.io team and I'll hand them the anonymised data very soon.

If you wish to obtain this dataset, my email is on the github profile. We could always discuss it.

**Comment by J5lx** [comment]
Okay, good to know, and thanks for the fast response. For now I think I'll be watching hackr.io then.
